default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: arandilopez
  password: arandilopez
  host: localhost
  port: 54320

development:
  <<: *default
  database: rails_graphql_nplus1_development

test:
  <<: *default
  database: rails_graphql_nplus1_test

production:
  <<: *default
  database: rails_graphql_nplus1_production
  username: rails_graphql_nplus1
  password: <%= ENV['RAILS_GRAPHQL_NPLUS1_DATABASE_PASSWORD'] %>
